/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liangchao_asuper_chaocwmpandroid_NativeCwmpMethod */

#ifndef _Included_com_liangchao_asuper_chaocwmpandroid_NativeCwmpMethod
#define _Included_com_liangchao_asuper_chaocwmpandroid_NativeCwmpMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liangchao_asuper_chaocwmpandroid_NativeCwmpMethod
 * Method:    getStringHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liangchao_asuper_chaocwmpandroid_NativeCwmpMethod_getStringHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
